language: kotlin
sudo: false
script:
  - scripts/run_etcd.sh
  - mvn clean verify
jdk:
  - oraclejdk8
notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/150c208eb635ec2c8dc0"
    on_success: change
    on_failure: always
    on_start: never
  email: false