language: kotlin
sudo: false
script:
  - scripts/run_etcd.sh
  - mvn clean verify
jdk:
  - oraclejdk8
notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/79de096a8e22b11c2355"
    on_success: change
    on_failure: always
    on_start: never
  email: false